apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chatbot-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["bind"]  # <-- THIS FIXES YOUR ISSUE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chatbot-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: chatbot-role
  apiGroup: rbac.authorization.k8s.io
